"""fix brief report columns

Revision ID: 615dfa3b142d
Revises: 
Create Date: 2026-02-12 10:28:31.465588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '615dfa3b142d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_brief_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('focus', sa.String(length=500), nullable=True, comment='分析关注点'),
    sa.Column('summary_data', sa.JSON(), nullable=True, comment='统计摘要数据(JSON)'),
    sa.Column('report_content', sa.Text(), nullable=True, comment='AI分析报告内容'),
    sa.Column('report_date', sa.DateTime(), nullable=True, comment='报告所属日期'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='brief'
    )
    op.create_table('call_history',
    sa.Column('mobile_phone', sa.String(length=20), nullable=False, comment='手机号码'),
    sa.Column('staff_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('sys_name', sa.String(length=50), nullable=False, comment='系统名称'),
    sa.Column('order_type', sa.String(length=50), nullable=False, comment='工单类型'),
    sa.Column('order_nums', sa.Integer(), nullable=False, comment='工单数量'),
    sa.PrimaryKeyConstraint('mobile_phone'),
    schema='calling'
    )
    op.create_table('call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('mobile_phone', sa.String(length=20), nullable=False, comment='手机号码'),
    sa.Column('staff_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('sys_name', sa.String(length=50), nullable=False, comment='系统名称'),
    sa.Column('order_type', sa.String(length=50), nullable=False, comment='工单类型'),
    sa.Column('order_nums', sa.Integer(), nullable=False, comment='工单数量'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态: 1=成功, 0=失败'),
    sa.Column('error_msg', sa.String(length=2000), nullable=True, comment='错误信息'),
    sa.Column('push_time', sa.DateTime(), nullable=False, comment='推送时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='calling'
    )
    op.create_index(op.f('ix_calling_call_log_mobile_phone'), 'call_log', ['mobile_phone'], unique=False, schema='calling')
    op.create_table('call_task',
    sa.Column('mobile_phone', sa.String(length=20), nullable=False, comment='手机号码'),
    sa.Column('staff_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('sys_name', sa.String(length=50), nullable=False, comment='系统名称'),
    sa.Column('order_type', sa.String(length=50), nullable=False, comment='工单类型'),
    sa.Column('order_nums', sa.Integer(), nullable=False, comment='工单数量'),
    sa.PrimaryKeyConstraint('mobile_phone'),
    schema='calling'
    )
    op.create_table('calling_task_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='任务ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('cron_expr', sa.String(length=100), nullable=False, comment='Cron 表达式'),
    sa.Column('source_schema', sa.String(length=100), nullable=False, comment='源数据 Schema'),
    sa.Column('source_table', sa.String(length=100), nullable=False, comment='源数据表名'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('field_mapping', sa.Text(), nullable=False, comment='字段映射 JSON'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='calling'
    )
    op.create_table('wxsafe_fz_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('clue_number', sa.String(length=100), nullable=False, comment='关联线索编号'),
    sa.Column('operator_id', sa.String(length=50), nullable=True, comment='操作人ID'),
    sa.Column('operator_name', sa.String(length=100), nullable=True, comment='操作人姓名'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='操作类型'),
    sa.Column('change_diff', sa.JSON(), nullable=True, comment='变更差异快照'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.PrimaryKeyConstraint('id'),
    schema='wxsafe'
    )
    op.create_index(op.f('ix_wxsafe_wxsafe_fz_log_clue_number'), 'wxsafe_fz_log', ['clue_number'], unique=False, schema='wxsafe')
    op.create_table('wxsafe_fz_master',
    sa.Column('clue_number', sa.String(length=100), nullable=False, comment='线索编号'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='涉诈或涉案'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='业务号码'),
    sa.Column('report_month', sa.String(length=20), nullable=True, comment='月份'),
    sa.Column('incident_time', sa.DateTime(), nullable=True, comment='涉诈（涉案）时间'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='涉诈涉案地（城市）'),
    sa.Column('fraud_type', sa.String(length=100), nullable=True, comment='涉诈类型'),
    sa.Column('victim_number', sa.Text(), nullable=True, comment='受害人号码'),
    sa.Column('is_compliant', sa.String(length=50), nullable=True, comment='是否合规受理'),
    sa.Column('has_resume_before', sa.String(length=50), nullable=True, comment='涉诈涉案前是否有复通'),
    sa.Column('is_resume_compliant', sa.String(length=50), nullable=True, comment='复通是否规范'),
    sa.Column('responsibility', sa.String(length=100), nullable=True, comment='责任认定'),
    sa.Column('is_self_or_family', sa.String(length=50), nullable=True, comment='是否本人或亲属涉诈涉案'),
    sa.Column('police_collab', sa.String(length=255), nullable=True, comment='警企协同情况'),
    sa.Column('investigation_note', sa.Text(), nullable=True, comment='调查户主备注'),
    sa.Column('abnormal_scene', sa.Text(), nullable=True, comment='异常场景识别'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='核查情况反馈'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='数据入库时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='数据最后更新时间'),
    sa.PrimaryKeyConstraint('clue_number'),
    schema='wxsafe'
    )
    op.create_index(op.f('ix_wxsafe_wxsafe_fz_master_phone_number'), 'wxsafe_fz_master', ['phone_number'], unique=False, schema='wxsafe')
    op.create_table('wxsafe_fz_detail',
    sa.Column('clue_number', sa.String(length=100), nullable=False, comment='线索编号'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='业务号码 (冗余)'),
    sa.Column('join_date', sa.DateTime(), nullable=True, comment='入网时间'),
    sa.Column('online_duration', sa.Integer(), nullable=True, comment='在网时长（月）'),
    sa.Column('install_type', sa.String(length=50), nullable=True, comment='新装或存量'),
    sa.Column('join_location', sa.String(length=100), nullable=True, comment='入网属地'),
    sa.Column('is_local_handle', sa.String(length=50), nullable=True, comment='属地或非属地办理'),
    sa.Column('owner_name', sa.String(length=100), nullable=True, comment='机主名称'),
    sa.Column('cert_address', sa.String(length=255), nullable=True, comment='证件地址'),
    sa.Column('customer_type', sa.String(length=50), nullable=True, comment='政企或个人'),
    sa.Column('other_phones', sa.Text(), nullable=True, comment='名下手机号码'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('agent_name', sa.String(length=100), nullable=True, comment='代理商'),
    sa.Column('store_name', sa.String(length=100), nullable=True, comment='受理厅店'),
    sa.Column('staff_id', sa.String(length=50), nullable=True, comment='受理人工号'),
    sa.Column('staff_name', sa.String(length=100), nullable=True, comment='受理人'),
    sa.Column('concurrent_cards', sa.Text(), nullable=True, comment='与涉诈号码同时办理的卡号'),
    sa.Column('package_name', sa.String(length=100), nullable=True, comment='所办理套餐'),
    sa.Column('is_fusion_package', sa.String(length=50), nullable=True, comment='是否融合套餐'),
    sa.Column('has_broadband', sa.String(length=50), nullable=True, comment='是否有宽带业务'),
    sa.Column('card_type', sa.String(length=50), nullable=True, comment='主卡或副卡'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='详情更新时间'),
    sa.ForeignKeyConstraint(['clue_number'], ['wxsafe.wxsafe_fz_master.clue_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clue_number'),
    schema='wxsafe'
    )
    op.create_index(op.f('ix_wxsafe_wxsafe_fz_detail_phone_number'), 'wxsafe_fz_detail', ['phone_number'], unique=False, schema='wxsafe')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_wxsafe_wxsafe_fz_detail_phone_number'), table_name='wxsafe_fz_detail', schema='wxsafe')
    op.drop_table('wxsafe_fz_detail', schema='wxsafe')
    op.drop_index(op.f('ix_wxsafe_wxsafe_fz_master_phone_number'), table_name='wxsafe_fz_master', schema='wxsafe')
    op.drop_table('wxsafe_fz_master', schema='wxsafe')
    op.drop_index(op.f('ix_wxsafe_wxsafe_fz_log_clue_number'), table_name='wxsafe_fz_log', schema='wxsafe')
    op.drop_table('wxsafe_fz_log', schema='wxsafe')
    op.drop_table('calling_task_config', schema='calling')
    op.drop_table('call_task', schema='calling')
    op.drop_index(op.f('ix_calling_call_log_mobile_phone'), table_name='call_log', schema='calling')
    op.drop_table('call_log', schema='calling')
    op.drop_table('call_history', schema='calling')
    op.drop_table('wx_brief_report', schema='brief')
    # ### end Alembic commands ###
